controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_auth_login:
    path:    /api/auth/login
    methods: [POST]

api_auth_refresh:
    path:    /api/auth/refresh
    methods: [POST]

superadmin_auth_login:
    path:    /superadmin/auth/login
    methods: [POST]
