web: vendor/bin/heroku-php-nginx -C docker/nginx/heroku.conf public/
worker: php bin/console messenger:consume async --time-limit=3600 -vv
release: php bin/console doctrine:migrations:migrate --no-interaction && php bin/console cache:clear
